import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "AI Course Generator",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // or "/favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GoogleOneTap />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
